version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped

  lap-time-api:
    build:
      context: .
      dockerfile: lap_time_api/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
